blender_version_min = "4.2.0"
id = "neigh_context_switcher"
license = ["SPDX:GPL-3.0-or-later"]
maintainer = "Neigh"
name = "Context Switcher"
schema_version = "1.0.0"
tagline = "Quick workspace and editor switching via popup at mouse location"
type = "add-on"
version = "1.1.0"
tags = ["User Interface"]
